language: python

python:
    - 2.7

services:
    - mongodb
    - redis-server

install:
    - git clone git@github.com:pengmeng/mongojuice.git
    - python ./mongojuice/setup.py install
    - pip install -r requirements.txt

script:
    - python -m unittest discover
